networks:
  overlay:

services:
  postgres:
    image: 'postgis/postgis:17-3.5'
    networks:
      - overlay
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: s57server
    volumes:
      - ./mount_data/postgres:/var/lib/postgresql/data

  postgressetup:
    build:
      context: ./postgres_init
      dockerfile: Dockerfile
    networks:
      - overlay
    restart: "no"
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./postgres_init/scripts:/postgres_init
    environment:
      PGUSER: admin
      PGPASSWORD: mysecretpassword
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: s57server
    entrypoint: [ "sh", "-c", "sleep 5 && /postgres_init/postgres_init.sh" ]

  memcached:
    image: memcached:1.6.37
    networks:
      - overlay
    ports:
      - "11211:11211"
    command: memcached -I 128m -m 512
    depends_on:
      - postgressetup

  s57server:
    image: ghcr.io/manimaul/njord-chart-server:1.0-SNAPSHOT
    networks:
      - overlay
    ports:
      - "9000:9000"
    environment:
      JAVA_OPTS: "-Dconfig.file=/opt/chart_server/application.conf \
        -Dcharts.webStaticContent=/opt/chart_server/public \
        -Djava.library.path=/opt/gdal/jni \
        -Dcharts.pgHost=postgres \
        -Dcharts.memcacheHost=memcached"
    depends_on:
      postgressetup:
        condition: service_completed_successfully
      memcached:
        condition: service_started
    volumes:
      - ./mount_data/s57server/application.conf:/opt/chart_server/application.conf
